--- 
services: 
  fedManager:
    build: .
    tty: true
    image: ""
    command: "sh start.sh FedManager"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    extra_hosts:
      - "cpswtng_archiva:"
    volumes:
      - undefined/input//fedManager:/root/Projects/c2wt/input
      - undefined/output//fedManager:/root/Projects/c2wt/logs
  JavaFederate_GLDFederate_0:
    build: .
    image: ""
    command: "sh start.sh GLDFederate,ExecJava" 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    extra_hosts:
      - "cpswtng_archiva:"
    links:
      - fedManager  
    volumes:
      - undefined/input//JavaFederate_GLDFederate_0:/root/Projects/c2wt/input
      - undefined/output//JavaFederate_GLDFederate_0:/root/Projects/c2wt/logs
  JavaFederate_TestFederate_0:
    build: .
    image: ""
    command: "sh start.sh TestFederate,ExecJava" 
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    extra_hosts:
      - "cpswtng_archiva:"
    links:
      - fedManager  
    volumes:
      - undefined/input//JavaFederate_TestFederate_0:/root/Projects/c2wt/input
      - undefined/output//JavaFederate_TestFederate_0:/root/Projects/c2wt/logs
version: "2.1"
